version: 2.1

workflows:
  build_and_test:
    jobs:
      - typecheck

jobs:
  typecheck:
    docker:
      - image: cimg/node:16.19
    #working_directory: /mnt/ramdisk/toolkit  # Speeds up caching
    steps:
      - checkout
      # Set cache dir on RAM disk for speed
      - run:
          name: "setcachedir"
          command: "yarn config set cache-folder /mnt/ramdisk/toolkit/.cache/yarn"
      # TODO: Create and run script to checksum all relevant files
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - cache-v0.1-{{ checksum "shell/latest/yarn.lock" }}
      - run:
          name: "Smoke Test"
          command: "tools/smoketest/smoke.sh ./"
      # Save Yarn package cache
      - save_cache:
          key: cache-v0.1-{{ checksum "shell/latest/yarn.lock" }}
          paths:
            - /mnt/ramdisk/toolkit/.cache/yarn
